

export enum MessageType {
    READY = "READY",
    MESSAGE_CREATE = "MESSAGE_CREATE",
    MESSAGE_UPDATE = "MESSAGE_UPDATE",
    MESSAGE_DELETE = "MESSAGE_DELETE",
    GUILD_MEMBER_LIST_UPDATE = "GUILD_MEMBER_LIST_UPDATE",
    GUILD_MEMBERS_CHUNK = "GUILD_MEMBERS_CHUNK",
}